# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73b6e140cac466c032f7c6fa3a46981d79848927057a21062aec8a4163bd40669a9986829931ea7529c190b6ff76c681a4b2cc3842ef35e39760ac3ce2372d0b
  
test:
  secret_key_base: 21db581f0a1517f598d6b92a6cf837732bf16e3b9e151ab175e9c1ea2fc8f26374df8405d6511830596c996812025a941473bd9e42e00bdd8780103909c961c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
